### ISSUE TITLE
Quick questions (not a real issue)

### ISSUE THREAD

**Issue by ogham** [petevine/RustBuild_v7#1]
Hi @petevine, I couldn't find a way to contact you so I hope this will do!

I bought a Raspberry Pi the other day so I could test my software on an ARM platform — it should be a lot easier for me to fix the issues in exa if I can actually see how the code runs. And now, after having set it all up, the Rust ARM community seems *way* smaller than I expected. You seem to know your way around, though, and I'd appreciate it if you answered a few questions I have.

- You configure a container to build Rust and Cargo in. Do I need to bother with this if I'm not actually going to use my Pi for anything other than ARM testing, or should I just follow the quick-start?
- What's `gnueabi divmod`? I searched but didn't understand what I was looking at! You recommend building LLVM, which seems like it would take *ages* (at least 2h55m) on such a tiny device.

Thanks in advance.

PS: The Pi reports itself as being `Linux raspberrypi 4.1.18-v7+ #846 SMP Thu Feb 25 14:22:53 GMT 2016 armv7l GNU/Linux`. I recognise the `arm` in `armv7l`, but that's it!

**Comment by petevine** [comment]
Hi,

Your Rpi is probably version 2 (4core, 1GB of ram) but it's still rather slow (up to 2x slower than the cited build time which totals over 7h including llvm).

Building your own rustc is possible but not necessary as long as binary builds are available. See warricksoth'r download links. (armv6 should work equally well)


Containers are great for ensuring compatible (old enough) versions of libraries are linked against; you don't have to bother with that if you're not going to offer your builds to the world. 

The patch is about soft division - it affects code performance but not correctness so you can safely wait until the next version of llvm gets bundled with rust. 

-original message-
Subject: [RustBuild_v7] Quick questions (not a real issue) (#1)
From: Benjamin Sago <notifications@github.com>
Date: 11.03.2016 15:02

Hi @petevine, I couldn't find a way to contact you so I hope this will do!

I bought a Raspberry Pi the other day so I could test my software on an ARM platform — it should be a lot easier for me to fix the issues in exa if I can actually see how the code runs. And now, after having set it all up, the Rust ARM community seems *way* smaller than I expected. You seem to know your way around, though, and I'd appreciate it if you answered a few questions I have.

- You configure a container to build Rust and Cargo in. Do I need to bother with this if I'm not actually going to use my Pi for anything other than ARM testing, or should I just follow the quick-start?
- What's `gnueabi divmod`? I searched but didn't understand what I was looking at! You recommend building LLVM, which seems like it would take *ages* (at least 2h55m) on such a tiny device.

Thanks in advance.

PS: The Pi reports itself as being `Linux raspberrypi 4.1.18-v7+ #846 SMP Thu Feb 25 14:22:53 GMT 2016 armv7l GNU/Linux`. I recognise the `arm` in `armv7l`, but that's it!

---
Reply to this email directly or view it on GitHub:
https://github.com/petevine/RustBuild_v7/issues/1

**Comment by petevine** [comment]
It's possible to build LLVM once and reuse it (or use the system installation).

If you're interested in the former see the latest issue I opened at RustBuild

**Comment by petevine** [comment]
Two more points:

- if you actually got an Rpi3, expect similar build times - see some benchmarks ([here](http://openbenchmarking.org/result/1603041-GA-1603024SO76) and [here](http://openbenchmarking.org/result/1603070-GA-1603052GA64))
- the preferred way to build an armv7 rustc should just be to pass:
`--build=armv7-unknown-linux-gnu` 
to configure, but it's still possible (but not very likely) you might encounter occasional problems with cargo dependencies (exa builds fine) which is why I prefer to keep the target name unchanged for now.
